name: Playwright tests

on:
  workflow_call:
    outputs:
      status:
        value: ${{ jobs.test.outputs.status }}

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ job.status }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'yarn'

      - name: Run tests
        env:
          PUBLIC_APP_URL: ${{ vars.PUBLIC_APP_URL }}
          PRIVATE_VERCEL_TEAM_ID: ${{ secrets.PRIVATE_VERCEL_TEAM_ID }}
          PRIVATE_VERCEL_TOKEN: ${{ secrets.PRIVATE_VERCEL_TOKEN }}
          SHA: ${{ github.sha }}

        run: |
          yarn
          yarn playwright install
          npx playwright test
